# Testing PGWire with fixed versions of clients
# This is meant to be run on every PR to catch regressions introduced by QuestDB code changes
# 4d1965c9142484e48d40c19de54b5cba84953a06 is the same as @v1, except it's guaranteed to be immutable
# even if the original tag is moved or deleted

name: Modified PGWire - Stable clients
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-build.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/questdb/questdb', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v4
    - run: touch optcd-3.txt
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: maven
    - run: touch optcd-4.txt
    - name: Build distribution
      run: mvn -B clean install -Dmaven.test.skip=true -Pbuild-binaries -pl '!benchmarks'
    - run: touch optcd-5.txt
    - name: Unpack distribution
      run: tar -xzf core/target/questdb-*-no-jre-bin.tar.gz
    - run: touch optcd-6.txt
    - name: Start QuestDB
      run: ./questdb-*bin/questdb.sh start
    - run: touch optcd-7.txt
    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: touch optcd-8.txt
    - name: Create and start virtual environment for psycopg2
      run: |-
        python3 -m venv venv_psycopg2
        source venv_psycopg2/bin/activate
        pip install -r compat/src/test/python/requirements_psycopg2_stable.txt
    - run: touch optcd-9.txt
    - name: Run tests with psycopg2
      run: |-
        source venv_psycopg2/bin/activate
        python compat/src/test/python/runner_psycopg2.py compat/src/test/resources/test_cases.yaml
    - run: touch optcd-10.txt
    - name: Create and start virtual environment for psycopg3
      run: |-
        python3 -m venv venv_psycopg3
        source venv_psycopg3/bin/activate
        pip install -r compat/src/test/python/requirements_psycopg3_stable.txt
    - run: touch optcd-11.txt
    - name: Run tests with psycopg3
      run: |-
        source venv_psycopg3/bin/activate
        python compat/src/test/python/runner_psycopg3.py compat/src/test/resources/test_cases.yaml
    - run: touch optcd-12.txt
    - name: Create and start virtual environment for asyncpg
      run: |-
        python3 -m venv venv_asyncpg
        source venv_asyncpg/bin/activate
        pip install -r compat/src/test/python/requirements_asyncpg_stable.txt
    - run: touch optcd-13.txt
    - name: Run tests with asyncpg
      run: |-
        source venv_asyncpg/bin/activate
        python compat/src/test/python/runner_asyncpg.py compat/src/test/resources/test_cases.yaml
    - run: touch optcd-14.txt
    - name: Activate Cargo Lock File
      run: |-
        cd compat/src/test/rust/scenarios
        cp ./Cargo.unlocked ./Cargo.lock
    - run: touch optcd-15.txt
    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@4d1965c9142484e48d40c19de54b5cba84953a06
      with:
        toolchain: 1.79.0
        cache-workspaces: compat/src/test/rust/scenarios
    - run: touch optcd-16.txt
    - name: Compile Rust scenarios runner
      run: |-
        cd compat/src/test/rust/scenarios
        cargo build --release
    - run: touch optcd-17.txt
    - name: Run Rust test runner
      run: |-
        compat/src/test/rust/scenarios/target/release/questrun_rust compat/src/test/resources/test_cases.yaml
    - run: touch optcd-18.txt
    - name: Stop QuestDB
      run: ./questdb-*bin/questdb.sh stop
    - run: touch optcd-19.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-build
        path: /home/runner/inotifywait-log-build.csv
    name: build
'on':
- push
- workflow_dispatch
